# -*- coding: utf-8 -*-
"""
/***************************************************************************
 autoclass
                                 A QGIS plugin
 deep learning based classifier
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-26
        copyright            : (C) 2021 by Shourya Shashank
        email                : shouryashashank@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load autoclass class from file autoclass.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .auto_class import autoclass
    return autoclass(iface)
